enum SpetoScreen {
  onboardingMarket,
  onboardingRestaurant,
  onboardingDeals,
  onboardingStudent,
  onboardingPro,
  login,
  register,
  studentRegister,
  forgotPassword,
  otpVerification,
  resetPassword,
  passwordSuccess,
  home,
  marketList,
  happyHourList,
  happyHourDetail,
  happyHourCheckout,
  restaurantList,
  restaurantDetail,
  menuItemDetail,
  eventsDiscovery,
  eventDetail,
  digitalTicket,
  ticketSuccess,
  orderHistory,
  orderTracking,
  orderReceipt,
  proPoints,
  addresses,
  paymentMethods,
  accountSettings,
  helpCenter,
  appMap,
}

enum NavSection { explore, orders, basket, points, profile }
